webclient/src/core/models.py
from datetime import datetime
from flask_login import current_user
from sqlalchemy.orm import validates
from src import db


def get_current_user_name():
    return current_user.email if current_user else "system"


class AutoIncrementMixin():
# Auto Generated Fields:
    id = db.Column(db.Integer, primary_key=True)


class ArchivedMixin():
# Auto Generated Fields:
    archived = db.Column(db.Boolean, default=False)


class AuditableMixin():
# Auto Generated Fields:
    # The Date of the Instance Creation => Created one Time when Instantiation
    created_on = db.Column(db.DateTime(timezone=True), default=datetime.now)
    # The User of the Instance Creation => Created one Time when Instantiation
    created_by = db.Column(db.String, default=get_current_user_name, onupdate=get_current_user_name)
    # The Date of the Instance Update => Changed with Every Update
    updated_on = db.Column(db.DateTime(timezone=True), default=datetime.now, onupdate=datetime.now)
    # The User of the Instance Update => Changed with Every Update
    updated_by = db.Column(db.String, default=get_current_user_name, onupdate=get_current_user_name)

webclient/src/accounts/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

from src import bcrypt, db, app
from src.accounts.models import User

from .forms import LoginForm, RegisterForm

accounts_bp = Blueprint("accounts", __name__, template_folder='templates', static_folder='static')


@accounts_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        flash("You are already registered.", "info")
        return redirect(url_for(app.config["ENTRY_ENDPOINT"]))
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()

        login_user(user)
        flash("You registered and are now logged in. Welcome!", "success")

        return redirect(url_for(app.config["ENTRY_ENDPOINT"]))

    return render_template("register.html", form=form)


@accounts_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in.", "info")
        return redirect(url_for(app.config["ENTRY_ENDPOINT"]))
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, request.form["password"]):
            login_user(user)
            return redirect(url_for(app.config["ENTRY_ENDPOINT"]))
        else:
            flash("Invalid email and/or password.", "danger")
            return render_template("login.html", form=form)
    return render_template("login.html", form=form)

@accounts_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("accounts.login"))

webclient/src/core/views.py
from flask import Blueprint, render_template
from flask_login import login_required

core_bp = Blueprint("core", __name__, template_folder='templates', static_folder='static', 
                    url_prefix='/core/')


@core_bp.route("/")
@login_required
def home():
    return render_template("index.html")

webclient/src/core/templates/includes/create_widget.html
{%- set id_prefix = '%s-' | format(context.model_name) if context.model_name | trim | lower else '' %}
      <form action="{{ context.create_url }}" method="post">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start flex-row-reverse">
{%- block close_button_block %}
          <div class="p-1">
            <button id="{{ id_prefix }}close-button" type="button" class="btn btn-link form-button">
              <a id="{{ id_prefix }}close-anchor" href="{{ context.close_url }}">{{ context.close_button_title }}</a>
            </button>
          </div>
{%- endblock close_button_block %}
{%- block create_button_block %}
          <div class="p-1">
            <input id="{{ id_prefix }}create-button" class="btn btn-primary" type="submit" value="{{ context.create_button_title }}">
          </div>
{%- endblock create_button_block %}
          <div class="p-9 flex-grow-1">
            <h1 class="content-title">{{ context.title | safe }}</h1>
          </div>
        </div>
        <hr>
        <div id="{{ id_prefix }}content-div" class="col-md-12">
{{- context.form.csrf_token }}
{{- context.form.hidden_tag() }}
          <dl>
{%- for field in context.fields -%}
  {% if context.is_field_hidden(field) %}
    {{- render_field(context.form[field], hidden=True) }}
  {% elif context.is_field_disabled(field) %}
    {{- render_field(context.form[field], readonly=True, disabled=True) }}
  {% else %}
    {{- render_field(context.form[field]) }}
  {%- endif %}
{%- endfor %}
          </dl>
        </div>
        <hr>
      </form>

webclient/src/core/templates/includes/list_widget.html
{%- set id_prefix = '%s-' | format(context.model_name) if context.model_name | trim | lower else '' %}
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start flex-row-reverse">
{%- block create_button_block %}
        <div class="p-1">
          <form method='get' action="{{ context.create_url }}">
            <div id="{{ id_prefix }}new-button" class="clearfix">
              <input class="float-end btn btn-primary" type="submit" value="{{ context.create_button_title }}"/>
            </div>
          </form>
        </div>
{%- endblock %}
        <div class="p-9 flex-grow-1">
          <h1 class="content-title">{{ context.title | safe }}</h1>
        </div>
      </div>
      <div id="{{ id_prefix }}list-div" class="col-md-12">
        <table id="{{ id_prefix }}list-table" class="table model-list">
          <thead>
            <tr>
{%- for field, label in context.labels.items() %}
              <th id="th-{{ id_prefix }}{{ field }}">{{ label }}</th>
{%- endfor %}
              <th id="th-{{ id_prefix }}action">Action</th>
            </tr>
          </thead>
          <tbody>
{%- for obj in context.objs %}
  {%- set obj_loop = loop %}
            <tr id="{{ id_prefix }}{{ obj.id }}" class="{{ obj.state }}" onclick="onRowClick(event)">
  {%- for field in context.fields %}
              <td id="td-{{ id_prefix }}{{ field }}">{{ context.getValue(obj, field) }}</td>
  {%- endfor %}
              <td id="td-{{ id_prefix }}action">
  {%- block delete_button_block scoped -%}
    {{ render_delete_small_button(obj.id, context.delete_button_title, obj_id_prefix=id_prefix) }}
  {%- endblock %}
                <form id="show-details-{{ id_prefix }}{{ obj.id }}" action="{{ context.retrieve_urls[obj_loop.index0] }}" method="get">
                </form>
              </td>
            </tr>
{%- endfor %}
{%- if context.objs | length == 0 -%}
            <tr><td colspan="{{ models | length }}">{{ context.empty_list_msg }}</td></tr>
{%- endif %}
          </tbody>
        </table>
      </div>
{{- render_delete_dlgs(context.delete_dialog_title,
                       context.delete_dialog_msg,
                       context.delete_dialog_submit_title,
                       context.delete_dialog_cancel_title,
                       context.delete_urls,
                       context.objs,
                       id_prefix) -}}

webclient/src/core/templates/includes/navigation.html
    <!-- Navigation -->
    <header class="p-3 text-bg-dark">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{{ url_for(config.ENTRY_ENDPOINT) }}" class="nav-link px-2 text-secondary">Home</a></li>
          </ul>
          <div class="text-end">
            {%- if current_user.is_authenticated %}
            <a href="{{ url_for('accounts.logout') }}"><button type="button" class="btn btn-danger me-2">Logout</button></a>
            {%- else %}
              <a href="{{ url_for('accounts.login') }}"><button type="button" class="btn btn-outline-light me-2">Login</button></a>
              <a href="{{ url_for('accounts.register') }}"><button type="button" class="btn btn-success">Sign up</button></a>
            {%- endif %}
          </div>
        </div>
      </div>
    </header>

webclient/src/core/templates/includes/retrieve_widget.html
{%- set id_prefix = '%s-' | format(context.model_name) if context.model_name | trim | lower else '' %}
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start flex-row-reverse">
{%- block close_button_block %}
        <div class="p-1">
          <button id="{{ id_prefix }}close-button" type="button" class="btn btn-link form-button">
            <a id="{{ id_prefix }}close-anchor" href="{{ context.close_url }}">{{ context.close_button_title }}</a>
          </button>
        </div>
{%- endblock %}
{%- block delete_button_block scoped %}
        <div class="p-1">
          {{- render_delete_button(context.form.id.data, context.delete_button_title, id_prefix ) }}
        </div>
{%- endblock delete_button_block %}
{%- block update_button_block %}
        <div class="p-1">
          <form action="{{ context.update_url }}" method="get">
            <input id="{{ id_prefix }}update-button" class="btn btn-primary form-button" type="submit" value="{{ context.update_button_title }}">
          </form>
        </div>
{%- endblock update_button_block %}
        <div class="p-9 flex-grow-1">
          <h1 class="content-title">{{ context.title | safe }}</h1>
        </div>
      </div>
      <hr>
      <div id="{{ id_prefix }}content-div" class="col-md-12">
{%- block form_block scoped %}
        <form action="{{ context.retrieve_url }}" method="get">
  {{- context.form.csrf_token }}
  {{- context.form.hidden_tag() }}
          <dl>
  {%- for field in context.fields %}
    {%- if context.is_field_hidden(field) %}
      {{- render_field(context.form[field], hidden=True) }}
    {%- else %}
      {{- render_field(context.form[field], readonly=True, disabled=True) }}
    {%- endif %}
  {%- endfor %}
          </dl>
        </form>
{%- endblock form_block %}
      </div>
      <hr>
{{- render_delete_dlg(context.delete_dialog_title,
                     context.delete_dialog_msg,
                     context.delete_dialog_submit_title,
                     context.delete_dialog_cancel_title,
                     context.delete_url,
                     context.form.id.data,
                     id_prefix) }}

webclient/src/core/templates/includes/update_widget.html
{%- set id_prefix = '%s-' | format(context.model_name) if context.model_name | trim | lower else '' %}
      <form action="{{ context.update_url }}" method="post">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start flex-row-reverse">
{%- block close_button_block %}
          <div class="p-1">
            <button id="{{ id_prefix }}close-button" type="button" class="btn btn-link form-button">
              <a id="{{ id_prefix }}close-anchor" href="{{ context.close_url }}">{{ context.close_button_title }}</a>
            </button>
          </div>
{%- endblock close_button_block %}
{%- block update_button_block %}
          <div class="p-1">
            <input id="{{ id_prefix }}update-button" class="btn btn-primary" type="submit" value="{{ context.update_button_title }}">
          </div>
{%- endblock update_button_block %}
          <div class="p-9 flex-grow-1">
            <h1 class="content-title">{{ context.title | safe }}</h1>
          </div>
        </div>
        <hr>
        <div id="{{ id_prefix }}content-div" class="col-md-12">
{{- context.form.csrf_token }}
{{- context.form.hidden_tag() }}
          <dl>
{%- for field in context.fields -%}
  {% if context.is_field_hidden(field) %}
    {{- render_field(context.form[field], hidden=True) -}}
  {% elif context.is_field_disabled(field) %}
    {{- render_field(context.form[field], readonly=True, disabled=True) }}
  {% else %}
    {{- render_field(context.form[field]) }}
  {%- endif %}
{%- endfor %}
          </dl>
        </div>
        <hr>
      </form>